name: markets
description: markets

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.5.2+20
# 1.0.0+4

environment:
  sdk: ">=2.18.0 <3.0.0"
module:
  androidX: true
dependencies:
  flutter:
    sdk: flutter
  mvc_pattern: 8.12.0 
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.3
  flutter_google_places_sdk: 0.4.2+1
  provider: ^6.1.2
  global_configuration: ^2.0.0
  http: ^1.2.2
  intl: ^0.20.2
  html: ^0.15.5
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  location: ^8.0.1
  theme_provider: ^0.6.0
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_messaging: ^16.0.0
  cloud_firestore: ^6.0.0
  firebase_analytics: ^12.0.0
  google_sign_in: ^7.1.1
  geolocator: ^10.1.1
  carousel_slider: ^5.0.0
  flutter_signin_button: ^2.0.0
  flutter_facebook_auth: ^7.1.2
  getwidget: ^7.0.0
  cached_network_image: ^3.4.1
  double_back_to_close_app: ^2.1.0
  another_flushbar: ^1.12.30
  permission_handler: ^12.0.1
  package_info_plus: ^4.1.0
  awesome_dialog: ^3.2.0
  rating_dialog: ^2.0.4
  sign_button: ^2.0.3
  responsive_grid: ^2.2.0
  google_maps_utils: ^2.0.0
  flex_color_scheme: ^8.0.0
  flutter_html: ^3.0.0
  google_maps_place_picker_mb: ^3.1.2
  card_swiper: ^3.0.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/img/visa.png
    - assets/img/paypal.png
    - assets/img/paypal2.png
    - assets/img/apple_pay.png
    - assets/img/brazil.png
    - assets/img/canada.png
    - assets/img/china.png
    - assets/img/france.png
    - assets/img/germany.png
    - assets/img/italy.png
    - assets/img/netherlands.png
    - assets/img/spain.png
    - assets/img/united-arab-emirates.png
    - assets/img/united-states-of-america.png
    - assets/img/marker.png
    - assets/img/my_marker.png
    - assets/img/mastercard.png
    - assets/img/visacard.png
    - assets/img/wallet.png
    - assets/img/cash.png
    - assets/img/pay_pickup.png
    - assets/img/logo.png
    - assets/img/Mriguel.jpg
    - assets/img/titleMedium.png
    - assets/img/backimg.png
    - assets/img/loading.gif
    - assets/img/google_play.png
    - assets/img/sold-out.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: AnnaCtt
    fonts:
      - asset: assets/fonts/AnnaCTT-Regular.ttf
        weight: 100
  - family: ProductSans
    fonts:
      - asset: assets/fonts/ProductSans-Thin.ttf
        weight: 100
      - asset: assets/fonts/ProductSans-Thin.ttf
        weight: 200
      - asset: assets/fonts/ProductSans-Light.ttf
        weight: 300
      - asset: assets/fonts/ProductSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/ProductSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/ProductSans-Bold.ttf
        weight: 600
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 700
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 800
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
